name: Docker Image CI

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'couchbase-server version'     
        required: true
        default: '6.5.0'

#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --build-arg VERSION=${{ github.event.inputs.version }} . --file Dockerfile --tag dockerimages/couchbase-server-sandbox:${{ github.event.inputs.version }}
#$(date +%s)
